# Site settings
title: Wedding!
email: wedding@hollyandandrew.co.uk
url: https://hollyandandrew.co.uk
description: "Holly Phillips and Andrew Miller are getting Married!"
share_image: /img/blah.png
keywords: theme jekyll config example

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#F9EACC'
  # primary-dark: '#F4E2BE'
  links: '#62892A'

# Footer settings
footer: Holly & Andy
footer_image: /img/line_holly_and_andy.png
site-icon: fa-heart-o
map-center-lat: 52.2006602
map-center-lng: 0.14

site-map:
    home:
        title: home
        js: true
        sections:
            - about
            - how_long
            - contact
            - map
        menu:
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    about:
        title: Welcome!
    how_long:
        title: How Long?
    contact:
        title: Contact Us
    map:
        title: Where?
    ceremony:
        title: Ceremony
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    reception:
        title: Evening
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    the-day:
        title: The Big Day
        submenu:
            - ceremony
            - reception
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    accommodation:
        title: Accommodation
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    rsvp:
        title: RSVP
        path: rsvp
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    giftlist:
        title: Gift List
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    todocambridge:
        title: Things to do in Cambridge
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist
            - faq
    faq:
        title: FAQ
        menu:
            - home
            - the-day
            - accommodation
            - rsvp
            - giftlist



# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-babel
  - jekyll-admin

# babel_js_extensions: 'es6, babel, jsx'
